# Generated by Django 4.1.2 on 2022-10-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image_url",
            field=models.URLField(verbose_name="Image URL"),
        ),
    ]
