# Generated by Django 4.1.2 on 2022-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_album", "0003_alter_album_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Album Name"
            ),
        ),
    ]
