# Generated by Django 4.1.1 on 2022-10-01 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Adventure", "Adventure"),
                            ("Puzzle", "Puzzle"),
                            ("Strategy", "Strategy"),
                            ("Sports", "Sports"),
                            ("Board/Card Game", "Board/Card Game"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(5.0),
                        ]
                    ),
                ),
                ("max_level", models.IntegerField(blank=True, default=1, null=True)),
                ("image_url", models.URLField()),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
