# Generated by Django 4.1.1 on 2022-10-18 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_game", "0002_alter_game_max_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image_url",
            field=models.URLField(verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="Value must be between 0.1 and 5.0"
                    ),
                    django.core.validators.MaxValueValidator(
                        5.0, message="Value must be between 0.1 and 5.0"
                    ),
                ]
            ),
        ),
    ]
