# Generated by Django 4.1.1 on 2022-10-28 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_game", "0003_alter_game_image_url_alter_game_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="max_level",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="The max level cannot be below 1"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="The rating can be between 0.1 and 5.0"
                    ),
                    django.core.validators.MaxValueValidator(
                        5.0, message="The rating can be between 0.1 and 5.0"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
