# Generated by Django 4.1.1 on 2022-10-28 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_game", "0004_alter_game_max_level_alter_game_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="max_level",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="The max level cannot be below 1"
                    )
                ],
                verbose_name="Max Level",
            ),
        ),
    ]
