# Generated by Django 4.1.1 on 2022-10-28 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_game", "0005_alter_game_max_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1, message="The rating can be between 0.1 and 5.0"
                    ),
                    django.core.validators.MaxValueValidator(
                        5.0, message="The rating can be between 0.1 and 5.0"
                    ),
                ],
            ),
        ),
    ]
