# Generated by Django 4.1.1 on 2022-10-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_game", "0006_alter_game_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "Action"),
                    ("Adventure", "Adventure"),
                    ("Puzzle", "Puzzle"),
                    ("Strategy", "Strategy"),
                    ("Sports", "Sports"),
                    ("Board/Card Game", "Board/Card Game"),
                    ("Other", "Other"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
