# Generated by Django 4.1.1 on 2022-10-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_profile", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
