# Generated by Django 4.1.1 on 2022-10-28 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_profile", "0002_delete_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        12, message="The age cannot be below 12"
                    )
                ]
            ),
        ),
    ]
